const NAV_ICON_LIGHT = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Crect width='16' height='16' rx='4' fill='%23e8f4ec'/%3E%3Crect x='3' y='9' width='2' height='2' rx='.5' fill='%2394c9a5'/%3E%3Crect x='7' y='6' width='2' height='2' rx='.5' fill='%2359a875'/%3E%3Crect x='11' y='3' width='2' height='2' rx='.5' fill='%23206e48'/%3E%3Cpath d='M3.5 6.5 7.5 9l5-5' fill='none' stroke='%23206e48' stroke-width='1.1' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E"
const NAV_ICON_DARK = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Crect width='16' height='16' rx='4' fill='%231a3d2c'/%3E%3Crect x='3' y='9' width='2' height='2' rx='.5' fill='%232a6b48'/%3E%3Crect x='7' y='6' width='2' height='2' rx='.5' fill='%233d9a64'/%3E%3Crect x='11' y='3' width='2' height='2' rx='.5' fill='%235ecf88'/%3E%3Cpath d='M3.5 6.5 7.5 9l5-5' fill='none' stroke='%235ecf88' stroke-width='1.1' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E"

export const usageInsightsCss = `
.dshi-page{
 --dshi-bg:var(--dsw-alias-bg-layer-2,#fff);--dshi-soft:var(--dsw-alias-bg-module-platform,#f5f7fa);--dshi-text:var(--dsw-alias-label-primary,#182c3c);--dshi-muted:var(--dsw-alias-label-tertiary,#667782);--dshi-line:var(--dsw-alias-border-l2,#e2e8ed);
 --dshi-accent:#17745d;--dshi-accent-soft:#edf7f3;--dshi-heat-0:#edf1f3;--dshi-heat-1:#cee8df;--dshi-heat-2:#8fc9b4;--dshi-heat-3:#459b7b;--dshi-heat-4:#176c53;--dshi-error:#b84c36;--dshi-blue:#6395ce;--dshi-purple:#a49ac7;--dshi-teal:#a3cabc;
 box-sizing:border-box;max-width:1200px;margin:0 auto;padding:30px clamp(16px,3.5vw,40px) 24px;color:var(--dshi-text);font:14px/1.55 -apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Microsoft YaHei',sans-serif;font-variant-numeric:tabular-nums;container-type:inline-size
}
body[data-ds-dark-theme] .dshi-page{--dshi-bg:var(--dsw-alias-bg-layer-2,#1d242b);--dshi-soft:var(--dsw-alias-bg-module-platform,#242d35);--dshi-text:var(--dsw-alias-label-primary,#edf3f6);--dshi-muted:var(--dsw-alias-label-tertiary,#a1afb9);--dshi-line:var(--dsw-alias-border-l2,#34414c);--dshi-accent:#73cbae;--dshi-accent-soft:#243e35;--dshi-heat-0:#2b363d;--dshi-heat-1:#294f43;--dshi-heat-2:#377c61;--dshi-heat-3:#4da480;--dshi-heat-4:#7dd8af;--dshi-error:#ef9b87;--dshi-teal:#58a392}
.dshi-page *{box-sizing:border-box}.dshi-page button{font:inherit;cursor:pointer}.dshi-page button:disabled{cursor:wait;opacity:.5}.dshi-page button:focus-visible,.dshi-page [tabindex]:focus-visible{outline:2px solid var(--dshi-accent);outline-offset:4px}.dshi-page button{touch-action:manipulation}.dshi-page h1,.dshi-page h2,.dshi-page p{margin:0}.dshi-page h1{font-size:24px;letter-spacing:-.7px;font-weight:650}.dshi-page h2{font-size:17px;letter-spacing:-.2px;font-weight:650}.dshi-page strong{font-weight:600}.dshi-caption{font-size:12px;color:var(--dshi-muted)}.dshi-eyebrow{display:block;font-size:12px;letter-spacing:.06em;color:var(--dshi-muted);margin-bottom:5px}
.dshi-top{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:24px}.dshi-top p{color:var(--dshi-muted);margin-top:7px}.dshi-title-row{display:flex;gap:12px;align-items:center}.dshi-brand-mark{width:29px;height:29px;display:flex;align-items:flex-end;gap:3px;padding:5px;border:1px solid var(--dshi-line);border-radius:7px}.dshi-brand-mark i{width:5px;background:var(--dshi-accent);border-radius:2px;height:45%}.dshi-brand-mark i:nth-child(2){height:75%;opacity:.7}.dshi-brand-mark i:nth-child(3){height:100%;opacity:.45}
.dshi-sync{display:inline-flex;align-items:center;gap:7px;white-space:nowrap;font-size:12px;color:var(--dshi-muted);padding:5px 9px;border:1px solid var(--dshi-line);border-radius:20px}.dshi-sync i{width:6px;height:6px;border-radius:50%;background:var(--dshi-muted)}.dshi-sync.ready i{background:var(--dshi-accent)}.dshi-sync.error i,.dshi-sync.partial i{background:var(--dshi-error)}
.dshi-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:20px;flex-wrap:wrap}.dshi-segmented{display:flex;gap:3px;border:1px solid var(--dshi-line);border-radius:9px;padding:3px;background:var(--dshi-soft)}.dshi-segmented button{border:0;background:transparent;color:var(--dshi-muted);padding:7px 16px;border-radius:6px;white-space:nowrap;font-size:13px;min-height:34px}.dshi-segmented button[aria-pressed=true]{background:var(--dshi-bg);color:var(--dshi-text);box-shadow:0 1px 4px #0000000d;font-weight:600}.dshi-segmented button:hover{color:var(--dshi-accent)}.dshi-segmented button span{font-size:12px;margin-left:4px;opacity:.65}.dshi-button{display:inline-flex;gap:8px;align-items:center;justify-content:center;border:1px solid var(--dshi-line);border-radius:8px;background:var(--dshi-bg);color:var(--dshi-muted);padding:8px 12px;font-size:13px!important;min-height:38px}.dshi-button:hover{border-color:var(--dshi-accent);color:var(--dshi-accent)}.dshi-button>span{font-size:18px;line-height:1}
.dshi-overview{display:grid;grid-template-columns:1fr 1.4fr;align-items:center;gap:24px;padding:26px 28px;border:1px solid var(--dshi-line);border-radius:12px;background:linear-gradient(115deg,var(--dshi-accent-soft),var(--dshi-bg) 65%);margin-bottom:20px}.dshi-total>strong{display:block;font-size:clamp(32px,4.5vw,46px);line-height:1.2;letter-spacing:-1.5px;color:var(--dshi-accent);margin:5px 0 8px}.dshi-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.dshi-metrics>div{padding-left:20px;border-left:1px solid var(--dshi-line)}.dshi-metrics>div>span{color:var(--dshi-muted);font-size:13px}.dshi-metrics strong{display:block;font-size:24px;letter-spacing:-.5px;margin-top:9px}.dshi-metrics small{font-size:12px;color:var(--dshi-muted);font-weight:400;margin-left:6px;white-space:nowrap}
.dshi-analysis-grid{display:grid;grid-template-columns:minmax(0,1fr) 255px;gap:16px;align-items:start}.dshi-panel{background:var(--dshi-bg);border:1px solid var(--dshi-line);border-radius:12px;padding:22px;min-width:0}.dshi-section-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:23px;flex-wrap:wrap}.dshi-section-head>.dshi-caption{text-align:right}.dshi-chart-scroll{overflow-x:auto;padding:4px 3px 6px;margin:0 -3px}.dshi-week-chart{min-width:455px}.dshi-week-row,.dshi-hour-axis{display:grid;grid-template-columns:42px repeat(24,minmax(0,1fr));gap:4px;align-items:center}.dshi-week-row{margin-top:5px}.dshi-day-label{font-size:12px;color:var(--dshi-muted)}.dshi-hour-axis{font-size:12px;color:var(--dshi-muted);margin-bottom:12px}.dshi-hour-axis>span{white-space:nowrap}.dshi-cell{aspect-ratio:1;min-height:13px;width:100%;padding:0;border:0;border-radius:3px}.dshi-page .l0{background:var(--dshi-heat-0)}.dshi-page .l1{background:var(--dshi-heat-1)}.dshi-page .l2{background:var(--dshi-heat-2)}.dshi-page .l3{background:var(--dshi-heat-3)}.dshi-page .l4{background:var(--dshi-heat-4)}.dshi-cell:hover{filter:brightness(.9)}.dshi-cell[aria-pressed=true],.dshi-month-day[aria-pressed=true]{outline:2px solid var(--dshi-accent);outline-offset:2px}.dshi-cell.has-unknown{box-shadow:inset 0 -2px var(--dshi-muted)}
.dshi-hour-bars{display:grid;grid-template-columns:repeat(24,minmax(0,1fr));gap:5px;min-width:455px;padding-top:4px}.dshi-hour-bar{border:0;background:none;padding:0;color:var(--dshi-muted);font-size:12px!important;text-align:left;min-width:0}.dshi-hour-bar>span:last-child{display:block;height:24px;white-space:nowrap;margin-top:8px}.dshi-bar-track{height:148px;display:flex;align-items:flex-end;border-bottom:1px solid var(--dshi-line);background:var(--dshi-soft);border-radius:3px 3px 0 0;overflow:hidden}.dshi-bar-track i{display:block;width:100%;background:var(--dshi-accent);opacity:.75;border-radius:3px 3px 0 0}.dshi-hour-bar:hover i,.dshi-hour-bar[aria-pressed=true] i{opacity:1}.dshi-hour-bar[aria-pressed=true] .dshi-bar-track{outline:2px solid var(--dshi-accent);outline-offset:1px}
.dshi-chart-foot{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:18px;flex-wrap:wrap}.dshi-legend{display:flex;gap:4px;align-items:center;font-size:12px;color:var(--dshi-muted);white-space:nowrap}.dshi-legend i{width:10px;height:10px;border-radius:2px}.dshi-legend span:first-child{margin-right:3px}.dshi-legend span:last-child{margin-left:3px}.dshi-chart-detail{border-top:1px solid var(--dshi-line);margin-top:19px;padding-top:16px;display:grid;grid-template-columns:1.2fr 1fr 1fr 1fr;gap:8px}.dshi-chart-detail>div{min-width:0}.dshi-chart-detail strong{display:block;margin-top:5px;font-size:14px;overflow-wrap:anywhere}.dshi-chart-detail small{font-size:12px;font-weight:400;color:var(--dshi-muted)}
.dshi-month-weekdays,.dshi-month-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:6px}.dshi-month-weekdays{font-size:12px;color:var(--dshi-muted);margin-bottom:10px;text-align:center}.dshi-month-day{border:1px solid var(--dshi-line);border-radius:6px;min-width:0;min-height:69px;padding:7px 5px;text-align:left;color:var(--dshi-text)}.dshi-month-day.l3,.dshi-month-day.l4{color:#fff}body[data-ds-dark-theme] .dshi-month-day.l3,body[data-ds-dark-theme] .dshi-month-day.l4{color:#101f18}.dshi-month-day>span:first-child{display:block;font-size:12px}.dshi-month-day>b{display:block;font-size:13px;letter-spacing:-.3px;margin:2px 0 5px}.dshi-micro-hours{display:grid;grid-template-columns:repeat(12,1fr);gap:1px}.dshi-micro-hours i{height:3px;border-radius:1px}.dshi-selected-hours{margin-top:18px;border-top:1px solid var(--dshi-line);padding-top:15px}.dshi-selected-hours>div{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;margin-top:10px}.dshi-selected-hours>div>span{font-size:12px;color:var(--dshi-muted);background:var(--dshi-soft);padding:6px;border-radius:5px}.dshi-selected-hours b{display:block;color:var(--dshi-text)}.dshi-selected-hours small{font-size:12px}
.dshi-stacked-bar{height:12px;border-radius:4px;overflow:hidden;display:flex;background:var(--dshi-soft);margin:8px 0 24px;gap:2px}.dshi-tone-input{background:var(--dshi-accent)}.dshi-tone-output{background:var(--dshi-blue)}.dshi-tone-read{background:var(--dshi-teal)}.dshi-tone-write{background:var(--dshi-purple)}.dshi-token-list>div{display:grid;grid-template-columns:1fr auto 35px;gap:8px;align-items:center;margin-top:17px;font-size:13px}.dshi-token-list>div>span:first-child{display:flex;align-items:center;gap:8px}.dshi-token-list>div>span:last-child{text-align:right}.dshi-dot{display:inline-block;width:7px;height:7px;border-radius:2px;flex-shrink:0}.dshi-reasoning{margin-top:24px;padding-top:15px;border-top:1px solid var(--dshi-line)}.dshi-reasoning>div{display:flex;justify-content:space-between;font-size:13px}.dshi-reasoning p{margin-top:7px}
.dshi-details{margin-top:20px}.dshi-details .dshi-section-head{margin-bottom:12px}.dshi-table-scroll{overflow-x:auto}.dshi-table{width:100%;border-collapse:collapse;text-align:left;min-width:510px;font-size:14px}.dshi-table th{padding:11px 12px;background:var(--dshi-soft);font-size:12px;color:var(--dshi-muted);font-weight:500}.dshi-table th:first-child{border-radius:5px 0 0 5px}.dshi-table th:last-child{border-radius:0 5px 5px 0}.dshi-table td{padding:15px 12px;border-bottom:1px solid var(--dshi-line)}.dshi-table td:first-child{max-width:300px;overflow-wrap:anywhere}.dshi-table td:first-child>span{display:block;margin-top:3px}.dshi-table td:not(:first-child),.dshi-table th:not(:first-child){text-align:right}.dshi-table tbody tr:last-child td{border-bottom:0}.dshi-share{display:flex;gap:10px;align-items:center;justify-content:flex-end}.dshi-share>span:last-child{min-width:34px}.dshi-share-track{width:75px;height:5px;border-radius:4px;background:var(--dshi-soft);overflow:hidden}.dshi-share-track i{display:block;height:100%;background:var(--dshi-accent);border-radius:4px}.dshi-results{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap;font-size:12px;color:var(--dshi-muted)}.dshi-success{color:var(--dshi-accent)}.dshi-failure{color:var(--dshi-error)}.dshi-table-foot{display:flex;align-items:center;justify-content:space-between;gap:12px;border-top:1px solid var(--dshi-line);padding-top:14px;flex-wrap:wrap}.dshi-text-button{border:0;background:none;padding:6px 0;color:var(--dshi-accent);font-size:13px!important}
.dshi-coverage{display:flex;gap:28px;align-items:center;background:var(--dshi-soft);border-radius:9px;margin-top:20px;padding:18px 22px}.dshi-coverage-summary{display:grid;grid-template-columns:1fr auto;column-gap:20px;min-width:150px}.dshi-coverage-label{font-size:12px;color:var(--dshi-muted)}.dshi-coverage-summary strong{font-size:16px}.dshi-coverage-track{height:4px;margin-top:9px;background:var(--dshi-line);grid-column:1/-1;border-radius:3px;overflow:hidden}.dshi-coverage-track i{height:100%;display:block;background:var(--dshi-accent)}.dshi-coverage-copy{font-size:12px;color:var(--dshi-muted)}.dshi-coverage-copy p+p{margin-top:4px}.dshi-footer{display:flex;justify-content:space-between;gap:12px;margin-top:18px;color:var(--dshi-muted);font-size:12px;flex-wrap:wrap}
.dshi-notice{padding:14px 16px;background:var(--dshi-soft);border:1px solid var(--dshi-line);border-radius:9px;margin-bottom:16px;display:flex;justify-content:space-between;align-items:center;gap:16px;font-size:13px}.dshi-notice p{margin-top:4px;font-size:12px}.dshi-notice.is-error{border-color:var(--dshi-error)}.dshi-loading,.dshi-empty{text-align:center;padding:64px 20px;color:var(--dshi-muted)}.dshi-loading strong,.dshi-empty strong{display:block;font-size:16px;color:var(--dshi-text);margin:14px 0 6px}.dshi-loading p,.dshi-empty p{font-size:13px}.dshi-loading-mark,.dshi-empty-symbol{display:inline-flex;align-items:center;justify-content:center;width:44px;height:44px;border:1px solid var(--dshi-line);border-radius:12px;color:var(--dshi-accent);font-size:24px}.dshi-empty{padding:32px 16px}
@container(max-width:850px){.dshi-analysis-grid{grid-template-columns:1fr}.dshi-composition .dshi-token-list{display:grid;grid-template-columns:1fr 1fr;gap:0 28px}.dshi-composition .dshi-section-head{margin-bottom:12px}.dshi-composition .dshi-stacked-bar{margin-bottom:5px}.dshi-composition .dshi-reasoning{margin-top:18px}.dshi-overview{padding:22px;gap:18px}.dshi-metrics{gap:10px}.dshi-metrics>div{padding-left:12px}}
@container(max-width:540px){.dshi-overview{grid-template-columns:1fr}.dshi-metrics{border-top:1px solid var(--dshi-line);padding-top:18px}.dshi-metrics>div:first-child{padding-left:0;border-left:0}.dshi-metrics strong{font-size:21px}.dshi-panel{padding:16px}.dshi-chart-detail{grid-template-columns:1fr 1fr;gap:14px}.dshi-top{align-items:flex-start}.dshi-top h1{font-size:22px}.dshi-top p{font-size:12px}.dshi-sync{font-size:12px}.dshi-segmented button{padding:7px 12px}.dshi-month-grid,.dshi-month-weekdays{gap:4px}.dshi-month-day{padding:5px 3px;min-height:64px}.dshi-micro-hours{display:none}.dshi-selected-hours>div{grid-template-columns:repeat(4,1fr)}.dshi-coverage{align-items:stretch;flex-direction:column;gap:12px;padding:16px}.dshi-composition .dshi-token-list{grid-template-columns:1fr}.dshi-notice{align-items:flex-start;flex-wrap:wrap}}
.dshi-nav>svg{display:none}.dshi-nav::before{content:"";display:block;width:16px;height:16px;flex:0 0 16px;background:center/contain no-repeat url("${NAV_ICON_LIGHT}")}body[data-ds-dark-theme] .dshi-nav::before{background-image:url("${NAV_ICON_DARK}")}
`

export function ensureUsageInsightsStyles(): void {
  if (document.getElementById('dsh-usage-analytics-style')) return
  const style = document.createElement('style'); style.id = 'dsh-usage-analytics-style'; style.textContent = usageInsightsCss
  document.head.append(style)
}

/** The Settings slot has no icon option in DSH rc.2; scope a replacement to our one nav row. */
export function installUsageInsightsNavIcon(): () => void {
  const mark = () => {
    for (const item of document.querySelectorAll('button')) {
      if (item.textContent?.trim() === '个人分析') item.classList.add('dshi-nav')
    }
  }
  mark()
  const observer = new MutationObserver(mark)
  observer.observe(document.body, { childList: true, subtree: true })
  return () => observer.disconnect()
}
